# Generated by Django 3.2.4 on 2021-10-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextmove', models.CharField(default='STRAIGHT', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_s', models.IntegerField(default=0)),
                ('head_x', models.IntegerField(default=1)),
                ('head_y', models.IntegerField(default=1)),
                ('food_x', models.IntegerField(default=1)),
                ('food_y', models.IntegerField(default=1)),
                ('done_s', models.BooleanField(default=False)),
                ('score_s', models.IntegerField(default=0)),
                ('direction_s', models.CharField(default='RIGHT', max_length=50)),
                ('col_l', models.BooleanField(default=False)),
                ('col_r', models.BooleanField(default=False)),
                ('col_u', models.BooleanField(default=False)),
                ('col_d', models.BooleanField(default=False)),
                ('mode_s', models.CharField(default=False, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('score', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='col_d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='col_l',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='col_r',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='col_u',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='direction_s',
            field=models.CharField(default='RIGHT', max_length=50),
        ),
        migrations.AddField(
            model_name='state',
            name='done_s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='mode_s',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='state',
            name='reward_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='score_s',
            field=models.IntegerField(default=0),
        ),
    ]
