# Generated by Django 3.2.4 on 2021-10-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211010_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_stats',
        ),
    ]
