# Generated by Django 3.2.4 on 2021-11-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_stats',
            name='highest_score',
        ),
        migrations.RemoveField(
            model_name='user_stats',
            name='time',
        ),
        migrations.AddField(
            model_name='state',
            name='user',
            field=models.CharField(default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='reward',
            name='direction_s',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='direction_s',
            field=models.CharField(max_length=50),
        ),
    ]
