# Generated by Django 3.2.4 on 2021-11-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_stats_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='trained_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('trained_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
